app/models.py
import datetime
from app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class Users(db.Model, UserMixin):
    """
    Create a Users table
    """
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True, unique=True)
    email = db.Column(db.String(60), unique=True)
    username = db.Column(db.String(60), unique=True)
    first_name = db.Column(db.String(60))
    last_name = db.Column(db.String(60))
    password_hash = db.Column(db.String(128))
    created_at = db.Column(db.DateTime, default=datetime.datetime.now)
    is_admin = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        """
        Prevent pasword from being accessed
        """
        raise AttributeError("Password is not readable attribute")

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return "<Users: {}>".format(self.email)


@login_manager.user_loader
def load_user(user_id):
    return Users.query.get(int(user_id))

class Links(db.Model):
    """
    Create an Links table
    """

    __tablename__ = 'links'

    id = db.Column(db.Integer, primary_key=True, unique=True)
    hash = db.Column(db.String(60), unique=True)
    phone = db.Column(db.String(21))
    redirect_url = db.Column(db.String(254))
    shorted_url = db.Column(db.String(150))
    created_at = db.Column(db.DateTime, default=datetime.datetime.now)

    def __repr__(self):
        return '<Links: {}>'.format(self.phone)


class Openned(db.Model):
    """
    Create a table for opened links
    """

    __tablename__ = 'openned'

    id = db.Column(db.Integer, primary_key=True, unique=True)
    link_id = db.Column(db.Integer)
    link_hash = db.Column(db.String(60))
    ip = db.Column(db.String(30))
    ga_client_id = db.Column(db.String(100))
    client_phone = db.Column(db.String(21))
    open_time = db.Column(db.DateTime, default=datetime.datetime.now)

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

# local imports
from config import app_config

from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()


def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')
    db.init_app(app)

    migrate = Migrate(app, db)
    from app import models

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .customers import customers as customers_blueprint
    app.register_blueprint(customers_blueprint)

    from .opened import opened as opened_blueprint
    app.register_blueprint(opened_blueprint)

    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page."
    login_manager.login_view = "auth.login"

    @app.errorhandler(404)
    def page_not_found(error):
        # This function handles all 404 error on the app and shows a custom 404
        # error page.
        return render_template('404.html', error=404)

    return app

app/customers/__init__.py
from flask import Blueprint

customers = Blueprint('customers', __name__)

from . import views

app/customers/views.py
from flask import render_template
from flask_login import login_required

from . import customers
from ..models import Links


@customers.route('/all')
@login_required
def all_customers():
    """
    Render the cutomers template on the / route
    """
    all_links = Links.query.all()

    return render_template('customers/customers.html', title="Tabela wszystkim utworzonych linkow dla klientów",
                           customers=all_links)

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
import json
import os

from flask import request, render_template
from flask_login import login_required

from . import home

from .. import db
from ..models import Links
from ..models import Openned

from .. import utils

if os.environ['FLASK_CONFIG'] == "development":
    HOST_NAME = "http://127.0.0.1:5000/"
else:
    HOST_NAME = "http://sekowski-url-shortener.herokuapp.com/"


@home.route('/')
@login_required
def homepage():
    """
    Render the homepage template on the / route
    """

    return render_template('home/index.html', title="Welcome")


@home.route('/addLink', methods=['POST'])
def add_link():
    url = request.form['link']
    phone = request.form['phone']

    if not url and not phone:
        return json.dumps({'info': 'Wypełnij poprawnie pola!'})

    if not utils.url_checker(url):
        return json.dumps({'info': 'Podany link jest błędny, spróbuj ponownie!'})

    link_hash = utils.random_string_generator(8)

    short_link = HOST_NAME + link_hash

    is_exist = Links.query.filter_by(hash=link_hash).first()
    if is_exist is None:
        customer = Links(hash=link_hash, phone=phone,
                         redirect_url=url,
                         shorted_url=short_link)

        db.session.add(customer)
        db.session.commit()

        print(link_hash, flush=True)
        return json.dumps({'info': short_link})
    else:
        return json.dumps({'info': 'Taki hash już istnieje spróboj ponownie!'})


@home.route('/<string:short_url>')
def redirect_to_templte(short_url):
    customer = Links.query.filter_by(hash=short_url).first()
    if customer is None:
        return render_template('home/index.html', title="Welcome", error="Url with this hash doesn't exist !")

    return render_template('redirect/index.html', title="Przekierowanie", text="Trwa przekierowanie",
                           hash=customer.hash)


@home.route('/redirect', methods=['POST'])
def redirect_to_url():
    client_hash = request.form['hash']
    ga_client_id = request.form['ga_client_id']

    link = Links.query.filter_by(hash=client_hash).first()

    if request.headers.getlist("X-Forwarded-For"):
        ip = request.headers.getlist("X-Forwarded-For")[0]
    else:
        ip = request.remote_addr

    open_link = Openned(link_id=link.id,
                        link_hash=link.hash,
                        ip=ip,
                        ga_client_id=ga_client_id,
                        client_phone=link.phone)
    db.session.add(open_link)
    db.session.commit()

    return json.dumps({'info': link.redirect_url})

app/opened/__init__.py
from flask import Blueprint

opened = Blueprint('opened', __name__)

from . import views

app/opened/views.py
from flask import render_template
from flask_login import login_required
from flask import make_response

try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
import csv
import datetime

from . import opened
from ..models import Openned


@opened.route('/opened')
@login_required
def show_opened():
    """
    Render the cutomers template on the / route
    """
    all_opened = Openned.query.all()

    return render_template('opened/opened.html', title="Tabela wszystkich zebranych info",
                           opened=all_opened)


@opened.route('/generatecsv')
@login_required
def generate_csv():
    all_opened = Openned.query.all()
    csv_list = []

    for open_info in all_opened:
        temp = []
        if open_info.client_phone is not None and open_info.ga_client_id is not None:
            temp.append(open_info.ga_client_id)
            temp.append(open_info.client_phone)
            csv_list.append(temp)

    dest = StringIO()
    writer = csv.writer(dest)

    for row in csv_list:
        writer.writerow(row)

    output = make_response(dest.getvalue())
    output.headers["Content-Disposition"] = "attachment; filename=export-{}.csv".format(datetime.date.today())
    output.headers["Content-type"] = "text/csv"
    return output

app/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
  <title>{{ title }} | URL SHORTENER</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}">
</head>
<body>
{% include 'header.html' %}
<div class="wrapper">
  {% block body %}
  {% endblock %}
</div>
{% include 'footer.html' %}
</body>
{% block scripts %}
  <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/additional-methods.min.js"></script>
  <script src="{{ url_for('static', filename='js/vendors/clipboard.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/vendors/jquery.mask.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/app.js') }}"></script>
{% endblock %}
</html>

app/templates/customers/customers.html
{% extends "base.html" %}
{% block title %}Customers{% endblock %}

{% block body %}
<div class="container">
  <h4 class="center-align">{{ title }}</h4>
  <table id="customers" class="display">
    <thead>
      <tr>
          <th>Nr. tel</th>
          <th>Utworzono</th>
          <th>Skrócony link</th>
          <th>Długi link</th>
      </tr>
    </thead>
    <tbody>
      {% for customer in customers|sort(attribute='created_at', reverse = True) %}
        <tr>
          <td>{{ customer.phone }}</td>
          <td>{{ customer.created_at }}</td>
          <td>{{ customer.shorted_url }}</td>
          <td>{{ customer.redirect_url }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/footer.html
<footer class="page-footer green darken-1">
  <div class="footer-copyright">
    <div class="container">
    Made by <a class="white-text text-lighten-3" href="mailto:miks.szymon@gmail.com">Szymon Miks</a>
    </div>
  </div>
</footer>

app/templates/header.html
<nav class="grey lighten-5" role="navigation">
  <div class="nav-wrapper container">
    <a id="logo-container" href="{{ url_for('home.homepage') }}" class="brand-logo">
      <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo"/>
    </a>
    <ul class="right hide-on-med-and-down">
      <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
      {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('customers.all_customers') }}">Customers</a></li>
        <li><a href="{{ url_for('opened.show_opened') }}">Opened</a></li>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Settigns<i class="material-icons right">arrow_drop_down</i></a>
          <ul class="dropdown-content">
            <li><a href="{{ url_for('auth.register') }}">Add user</a></li>
            <li><a href="{{ url_for('auth.all_users') }}">Show all user</a></li>
          </ul>
        </li>
        <li class="nav-user-button"><a><i class="material-icons left">account_circle</i> Hi, {{ current_user.username }}!</a>
        </li>
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      {% else %}
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
      {% endif %}
    </ul>

    <ul id="nav-mobile" class="side-nav" style="transform: translateX(-100%);">
      <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
      {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('customers.all_customers') }}">Customers</a></li>
        <li><a href="{{ url_for('opened.show_opened') }}">Opened</a></li>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Settigns<i class="material-icons right">arrow_drop_down</i></a>
          <ul class="dropdown-content">
            <li><a href="{{ url_for('auth.register') }}">Add user</a></li>
            <li><a href="{{ url_for('auth.all_users') }}">Show all user</a></li>
          </ul>
        </li>
        <li class="nav-user-button"><a><i class="material-icons left">account_circle</i> Hi, {{ current_user.username }}!</a>
        </li>
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      {% else %}
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
      {% endif %}
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>

app/templates/home/index.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block body %}
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br>
      <h1 class="header center blue-text lighten-1-text">Skracacz linków</h1>
      <div class="row center">
        <h5 class="header col s12 light">Dla kajakisekowski.pl</h5>
      </div>
      <br>

    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col xl6 offset-xl3 s12">

        <div id="card-alert" class="card red" style="{{ 'display:block' if  error  else 'display:none' }}">
          <div class="card-content white-text">
            <p class="center-align"><i class="mdi-alert-error"></i> {{ error }}</p>
          </div>
        </div>

        <div class="row">
          <form id="link-form" method="POST" class="col s12">
            <div class="row">
              <div class="input-field col s12">
                <input id="phone" name="phone" type="text" class="validate">
                <label for="phone">Phone</label>
              </div>
              <div class="input-field col s12">
                <input id="url_to_short" name="url_to_short" type="text" class="validate">
                <label for="url_to_short">Url to short</label>
              </div>
              <div class="col s12 center-align">
                <button class="btn waves-effect waves-light" type="submit">Skróć
                  <i class="material-icons right">send</i>
                </button>
              </div>
            </div>
          </form>


          <div class="col s12 m12">
            <div class="ajax-info deep-purple lighten-5 z-depth-1">
              <div class="ajax-text">
                <p><i class="material-icons">info_outline</i> INFO : <span></span></p>
              </div>
              <div class="progress">
                <div class="indeterminate"></div>
              </div>
            </div>
            <div class="copy-input-wrapper z-depth-2">
              <input id="copy-input" value="">
              <button class="btn copy" data-clipboard-target="#copy-input"
                      onclick="Materialize.toast('Link skopiowany', 4000)">
                <img class="clippy-img" src="{{ url_for('static', filename='img/clippy.svg') }}"
                     alt="Copy to clipboard">
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/opened/opened.html
{% extends "base.html" %}
{% block title %}Opened{% endblock %}

{% block body %}
  <div class="container">
    <h4 class="center-align">{{ title }}</h4>
    <div class="col s12 right mb16">
      <a class="btn" href="/generatecsv">Export to CSV</a>
    </div>
    <table id="opened" class="display">
      <thead>
      <tr>
        <th>Kiedy otwarty</th>
        <th>Telefon</th>
        <th>GA Client ID</th>
        <th>Link hash</th>
        <th>IP</th>
      </tr>
      </thead>
      <tbody>
      {% for open in opened|sort(attribute='open_time', reverse = True) %}
        <tr>
          <td>{{ open.open_time }}</td>
          <td>{{ open.client_phone }}</td>
          <td>{{ open.ga_client_id }}</td>
          <td>{{ open.link_hash }}</td>
          <td>{{ open.ip }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

app/templates/redirect/index.html
<!doctype html>
<html lang="pl">
<head>
  <meta charset="utf-8">

  <title>{{ title }}</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}">

{#  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">#}
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-57542624-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }

    gtag('js', new Date());
    gtag('config', 'UA-57542624-1');
  </script>
  <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous">
  </script>
  <script src="{{ url_for('static', filename='js/redirect.js') }}"></script>

  <style>
    html, body {
      height: 100%;
    }

    html {
      display: table;
      margin: auto;
    }

    body {
      display: table-cell;
      vertical-align: middle;
    }

    #loader-wrapper {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: 1000
    }

    .company-logo {
      position: relative;
      z-index: 999999;
      text-align: center;
    }

    .redirect-text {
      z-index: 9999999;
      position: relative;
      margin-top: 16em;
    }

    .redirect-text span {
      font-size: 26px;
      font-family: monospace;
      font-weight: bold;
    }

    #loader-wrapper .loader-section {
      position: fixed;
      top: 0;
      width: 51%;
      height: 100%;
      background: #eceff1;
      z-index: 1000;
      -webkit-transform: translateX(0);
      -ms-transform: translateX(0);
      transform: translateX(0)
    }

    #loader-wrapper .loader-section.section-left {
      left: 0
    }

    #loader-wrapper .loader-section.section-right {
      right: 0
    }

    #loader {
      display: block;
      position: relative;
      left: 50%;
      top: 50%;
      width: 150px;
      height: 150px;
      margin: -75px 0 0 -75px;
      border-radius: 50%;
      border: 3px solid transparent;
      border-top-color: #3498db;
      -webkit-animation: spin 2s linear infinite;
      animation: spin 2s linear infinite;
      z-index: 1001
    }

    #loader:before {
      content: "";
      position: absolute;
      top: 5px;
      left: 5px;
      right: 5px;
      bottom: 5px;
      border-radius: 50%;
      border: 3px solid transparent;
      border-top-color: #e74c3c;
      -webkit-animation: spin 3s linear infinite;
      animation: spin 3s linear infinite
    }

    #loader:after {
      content: "";
      position: absolute;
      top: 15px;
      left: 15px;
      right: 15px;
      bottom: 15px;
      border-radius: 50%;
      border: 3px solid transparent;
      border-top-color: #f9c922;
      -webkit-animation: spin 1.5s linear infinite;
      animation: spin 1.5s linear infinite
    }

    @-webkit-keyframes spin {
      0% {
        -webkit-transform: rotate(0deg);
        -ms-transform: rotate(0deg);
        transform: rotate(0deg)
      }

      100% {
        -webkit-transform: rotate(360deg);
        -ms-transform: rotate(360deg);
        transform: rotate(360deg)
      }
    }

    @keyframes spin {
      0% {
        -webkit-transform: rotate(0deg);
        -ms-transform: rotate(0deg);
        transform: rotate(0deg)
      }

      100% {
        -webkit-transform: rotate(360deg);
        -ms-transform: rotate(360deg);
        transform: rotate(360deg)
      }
    }

    .loaded #loader-wrapper {
      visibility: hidden;
      -webkit-transform: translateY(-100%);
      -ms-transform: translateY(-100%);
      transform: translateY(-100%);
      -webkit-transition: all 0.3s 1s ease-out;
      transition: all 0.3s 1s ease-out
    }

    .loaded #loader-wrapper .loader-section.section-left {
      -webkit-transform: translateX(-100%);
      -ms-transform: translateX(-100%);
      transform: translateX(-100%);
      -webkit-transition: all 0.7s 0.3s cubic-bezier(0.645, 0.045, 0.355, 1);
      transition: all 0.7s 0.3s cubic-bezier(0.645, 0.045, 0.355, 1)
    }

    .loaded #loader-wrapper .loader-section.section-right {
      -webkit-transform: translateX(100%);
      -ms-transform: translateX(100%);
      transform: translateX(100%);
      -webkit-transition: all 0.7s 0.3s cubic-bezier(0.645, 0.045, 0.355, 1);
      transition: all 0.7s 0.3s cubic-bezier(0.645, 0.045, 0.355, 1)
    }

    .loaded #loader {
      opacity: 0;
      -webkit-transition: all 0.3s ease-out;
      transition: all 0.3s ease-out
    }
  </style>
</head>

<body>
<div class="company-logo">
  <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo"/>
</div>
<div id="loader-wrapper">
  <div id="loader"></div>
  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>
</div>
<div class="redirect-text">
  <span>{{ text }}</span>
  <input id="hash" type="hidden" value="{{ hash }}">
</div>
</body>

</html>